server:
  port: 11112
  servlet:
    context-path: /oge-dag-22
  tomcat:
    relaxed-query-chars: [ '|','{','}','[',']' ]
    relaxed-path-chars: [ '|','{','}','[',']' ]

spring:
  redis:
    database: 0
    host: 125.220.153.26
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: 'ypfamily608'
    port: 6379

python:
#  execute-sh: /home/geocube/oge/oge-server/python-server/ogescript_execute.sh
#  store-dir: /home/geocube/oge/oge-server/python-server/python-script/
  execute-sh: /home/wkx/oge/sh/ogeScriptExecute.sh
  store-dir: /home/wkx/oge/python_tools/oge-script/

