server:
  port: 8085
  #  port: 11112
  servlet:
    context-path: /oge-dag-22
  tomcat:
    relaxed-query-chars: [ '|','{','}','[',']' ]
    relaxed-path-chars: [ '|','{','}','[',']' ]

spring:
  redis:
    database: 0
#    host: 10.101.240.21
    host: 125.220.153.26
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: 'ypfamily608'
    port: 6379
  datasource:
    url: jdbc:postgresql://125.220.153.23:30865/oge
    driver-class-name: org.postgresql.Driver
    username: oge
    password: ypfamily608
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update


#python-file:
#  execute-sh: /home/oge/oge-server/python-server/ogeScriptExecute.sh
#  store-dir: /home/oge/oge-server/python-server/oge-script/

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:whu/edu/cn/ogedagboot/**/xml/*Dao.xml

mybatis-plus:
  mapper-locations: classpath*:whu/edu/cn/ogedagboot/**/xml/*Dao.xml
  #  global-config:
  #configuration:
  #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
